### ISSUE TITLE
Disable the "Copy Results" button when there are no results to copy

### ISSUE THREAD

**Issue by anushibinj** [anushibin007/jira-bulk-sub-task-creator#3]
On a blank screen with no input items, there is no point in having the "Copy Results" button active. So, disable it in that case.

**Comment by Kamalraj5544** [comment]
can i work on this ?

**Comment by anushibinj** [comment]
@Kamalraj5544, Sure. you may :)

**Comment by Kamalraj5544** [comment]
done :) @anushibin007

**Comment by anushibinj** [comment]
**UPDATE:** PR #4 was created by @Kamalraj5544

**Comment by anushibinj** [comment]
**CLOSED:** PR #4 by @Kamalraj5544 fixes this issue.
